version: '3'
services:
  php:
    build:
      context: .
    volumes:
      - ./:/var/www/html
    links:
      - mysql

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/dev/default.conf:/etc/nginx/conf.d/default.conf:ro
    links:
      - php

  mysql:
    image: mysql:8.0
    user: mysql
    volumes:
      - ./docker/.data/db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    command: ["--default-authentication-plugin=mysql_native_password"]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
    links:
      - mysql
      - php